version: '3.9'

# services
services:
  test_db:
    image: postgres:latest
    container_name: test_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_DB=test

  api:
    container_name: node_v1
    build:
      context: .
      dockerfile: Dockerfile
    hostname: localhost
    ports:
      - 8080:8080
    command: npm run start
